FROM ubuntu:24.04

RUN apt update && \
    apt install -y wget lsb-release && \
    wget https://cvmrepo.s3.cern.ch/cvmrepo/apt/cvmfs-release-latest_all.deb && \
    dpkg -i cvmfs-release-latest_all.deb && \
    rm -f cvmfs-release-latest_all.deb && \
    apt update && \
    apt install -y cvmfs && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/cvmfs/keys/eessi.io
COPY eessi/software.eessi.io.conf /etc/cvmfs/config.d/
COPY eessi/eessi.io.pub /etc/cvmfs/keys/eessi.io/

#Specific to ubuntu startpoint since user already exists
RUN groupmod ubuntu -n jovyan
RUN usermod ubuntu -l jovyan -d /home/jovyan
RUN mkdir -p /home/jovyan
RUN chown -R jovyan:jovyan /home/jovyan

COPY entrypoint-sidecar.sh /entrypoint-sidecar.sh
RUN chmod +x /entrypoint-sidecar.sh

ENTRYPOINT ["/entrypoint-sidecar.sh"]
