services:
  jupyter-docker-extension:
    image: ${DESKTOP_PLUGIN_IMAGE}
  jupyter:
    image: eessi_jlab
    container_name: eessi_jupyter_embedded_dd_vm
    restart: unless-stopped
    volumes:
      - cvmfs-cache:/cvmfs-cache
      - jupyter_data:/home/eessi-user
    # Required for CVMFS to be able to mount the filesystem
    privileged: true
    ports:
      - 57438:8888

volumes:
  jupyter_data:
  cvmfs-cache:
